name: Lint and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: yarn install
      - run: npx nx affected --target=lint --fix --parallel --base=main --head=HEAD
      - run: npx nx format:write --uncommitted
      - run: npx nx e2e docs-react-e2e --prod
